// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lwzXqerqxL0DOAUGiOIL11ntxKo-AKE',
    appId: '1:780248709287:web:5aaac948e932065f6f0382',
    messagingSenderId: '780248709287',
    projectId: 'fir-flutter-codelab-a2480',
    authDomain: 'fir-flutter-codelab-a2480.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a2480.appspot.com',
    measurementId: 'G-5M3R5N02P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiizjGsLzN8top7qthqqtJVHUKQkkAph8',
    appId: '1:780248709287:android:aee315e0bf19099b6f0382',
    messagingSenderId: '780248709287',
    projectId: 'fir-flutter-codelab-a2480',
    storageBucket: 'fir-flutter-codelab-a2480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJDZS8hhUX01aWIDYfgxEUlkka3BdRUlM',
    appId: '1:780248709287:ios:89ed5012b7b321df6f0382',
    messagingSenderId: '780248709287',
    projectId: 'fir-flutter-codelab-a2480',
    storageBucket: 'fir-flutter-codelab-a2480.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJDZS8hhUX01aWIDYfgxEUlkka3BdRUlM',
    appId: '1:780248709287:ios:89ed5012b7b321df6f0382',
    messagingSenderId: '780248709287',
    projectId: 'fir-flutter-codelab-a2480',
    storageBucket: 'fir-flutter-codelab-a2480.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
